enableGlobalCache: false
packageExtensions:
  {
    "@jest/test-result@*":
      { dependencies: { jest-haste-map: "*", jest-resolve: "*" } },
    "jest-cli@*": { dependencies: { "@types/yargs": "*" } },
  }
